micronaut:
  application:
    name: mnTestR2dbcTransactions
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    url: jdbc:h2:mem:testdb
    username: 'sa'
    password: ''
r2dbc:
  datasources:
    default:
      url: r2dbc:h2:mem:///testdb
      username: 'sa'
      password: ''
